name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up SSH
        run: |
          echo "$SSH_PRIVATE_KEY" > keyfile
          chmod 600 keyfile
          mkdir -p ~/.ssh
          echo "Host ec2-13-60-25-157.eu-north-1.compute.amazonaws.com" > ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          ssh-keyscan -H ec2-13-60-25-157.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: SSH and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -T -i keyfile ubuntu@ec2-13-60-25-157.eu-north-1.compute.amazonaws.com "sudo bash ~/deploy.sh"
